<?php
return [
	'centralvt' => [
		'name' => 'Central VT',
		'type' => 'Modernização da operação digital',
		'status' => 'Conta em curso',
		'status_tone' => 'progress',
		'title' => 'Central VT | Automação e produção da operação digital',
		'description' => 'Três frentes na mesma operação: comunicação documental entregue, caminho até a produção em implantação e automação comercial em desenvolvimento.',
		'lead' => 'Estruturação da operação digital: publicar com controle, rastrear documentos e, em seguida, automatizar o primeiro contato comercial.',
		'problem' => 'A operação misturava aplicação sem processo completo de publicação, comunicação documental sem rastreio e um primeiro contato comercial ainda manual.',
		'solution' => 'Três frentes complementares: DocuTrace para o documento, engenharia de produção no Google Cloud e LeadFlow para o caminho entre o formulário e o atendimento.',
		'result' => 'O DocuTrace está entregue. A produção em cloud já roda, com pipeline automatizada ainda em implantação. O LeadFlow está desenhado, sem resultado operacional medido.',
		'highlights' => ['Três frentes, um cliente', 'Status honesto por frente', 'Produção sem chave permanente (em implantação)', 'LeadFlow ainda em desenvolvimento'],
		'metrics' => [
			['value' => '3', 'label' => 'frentes na mesma conta'],
			['value' => '1', 'label' => 'frente já entregue'],
			['value' => 'Cloud', 'label' => 'produção em implantação'],
		],
		'technologies' => ['Docker', 'Google Cloud Run', 'GitLab CI/CD', 'APIs', 'PHP', 'PostgreSQL'],
		'visual' => 'diagram',
	],
	'docutrace' => [
		'name' => 'DocuTrace',
		'type' => 'Comunicação documental rastreável',
		'status' => 'Entregue',
		'status_tone' => 'done',
		'title' => 'DocuTrace | Comunicação documental rastreável',
		'description' => 'Campanhas, portal protegido e registro separado de entrega, acesso, download e manifestação — sem se apresentar como assinatura digital.',
		'lead' => 'A comunicação deixa de depender de planilha, conferência manual e link público. Passa a ser centralizada, pesquisável e mensurável.',
		'problem' => 'Enviar uma atualização contratual respondia só parte das perguntas: quem tentamos alcançar, o que o provedor aceitou. Não dava para saber, com clareza, quem chegou ao documento, quem baixou e quem se manifestou.',
		'solution' => 'Catálogo de destinatários, campanha vinculada a uma versão do PDF, token individual, portal sem listagem pública e trilha de eventos separados: envio, entrega, visualização, download e aceite ou recusa quando houver.',
		'result' => 'A operação documental fica controlada. O painel distingue abertura de e-mail de visualização do contrato. O sistema não é assinatura digital nem garantia jurídica isolada — é rastreio operacional da comunicação.',
		'highlights' => ['Portal protegido', 'Token por destinatário', 'Eventos distintos', 'Relatório por campanha'],
		'metrics' => [
			['value' => 'Entregue', 'label' => 'projeto em operação'],
			['value' => 'Token', 'label' => 'acesso individual'],
			['value' => 'Trilha', 'label' => 'envio, acesso, download'],
			['value' => 'Não', 'label' => 'não é assinatura digital'],
		],
		'technologies' => ['Aplicação web', 'Portal protegido', 'E-mail transacional', 'Worker', 'Relatórios'],
		'note' => 'Prints de demonstração, quando usados, levam dados fictícios. Visualização do documento não equivale a assinatura.',
	],
	'leadflow' => [
		'name' => 'LeadFlow',
		'type' => 'Automação do primeiro contato comercial',
		'status' => 'Em desenvolvimento',
		'status_tone' => 'build',
		'title' => 'LeadFlow | Do formulário ao agendamento comercial',
		'description' => 'Automação desenhada para registrar o contato, separar comercial de suporte e responder sem fila humana. Ainda sem resultado medido em produção.',
		'lead' => 'Resultado esperado: o primeiro contato deixa de depender de alguém consultar, cadastrar e responder cada formulário na mão.',
		'problem' => 'O caminho atual é site, formulário, Discord, consulta manual, cadastro no help desk, WhatsApp e agenda. Isso atrasa o retorno, mistura suporte com comercial e depende de uma pessoa em cada etapa.',
		'solution' => 'Persistir o contato antes de qualquer classificação. Regras locais separam comercial, suporte e indefinido. A IA entra só no residual. Materiais e agenda saem automaticamente; falhas reprocessam sem perder o registro.',
		'result' => 'Resultado esperado — ainda não medido: menos intervenção entre o primeiro contato e o agendamento, sem enviar apresentação comercial a quem só queria suporte. A implantação ainda não está em produção.',
		'highlights' => ['Salvar antes de classificar', 'Regra antes da IA', 'Comercial separado de suporte', 'Reprocessamento sem perda'],
		'metrics' => [
			['value' => 'MVP', 'label' => 'desenho e recorte definidos'],
			['value' => 'Regra', 'label' => 'IA só no residual'],
			['value' => 'Esperado', 'label' => 'ainda sem métrica de produção'],
		],
		'technologies' => ['PHP', 'MySQL', 'SMTP', 'DeepInfra', 'WordPress'],
		'note' => 'Estado: em desenvolvimento. Nenhum percentual de redução de trabalho manual deve ser lido como resultado já obtido.',
	],
	'smat' => [
		'name' => 'SMAT',
		'type' => 'Disponibilidade e autorrecuperação',
		'status' => 'Em operação',
		'status_tone' => 'done',
		'title' => 'SMAT | Monitoramento especializado e autorrecuperação',
		'description' => 'Monitoramento por aplicação, visão das dependências e ações predefinidas para reduzir indisponibilidade em regime 24×7.',
		'lead' => 'O plantonista deixa de começar o diagnóstico no escuro quando a falha está em um sistema dependente.',
		'problem' => 'Durante a madrugada, o sintoma visto pelo usuário nem sempre estava no sistema reportado. O diagnóstico alongava a indisponibilidade.',
		'solution' => 'Monitoramento segundo as regras de cada aplicação, correlação de dependências, dashboard e execução de soluções conhecidas. Zabbix permanece em servidores e rede; o SMAT cobre a lógica das aplicações.',
		'result' => 'Menos tempo de indisponibilidade e menos acionamento evitável. Quando a pessoa entra, já encontra uma visão consolidada.',
		'highlights' => ['Monitoramento por aplicação', 'Dependências mapeadas', 'Autorrecuperação', 'Apoio ao plantão'],
		'metrics' => [
			['value' => '24×7', 'label' => 'monitoramento contínuo'],
			['value' => 'N2/N3', 'label' => 'apoio ao diagnóstico'],
			['value' => 'Auto', 'label' => 'ações predefinidas'],
		],
		'technologies' => ['Python', 'PowerShell', 'Shell Script', 'PHP', 'MySQL', 'APIs'],
	],
	'smap' => [
		'name' => 'SMAP',
		'type' => 'Monitoramento eleitoral automatizado',
		'status' => 'Operou em 2024',
		'status_tone' => 'done',
		'title' => 'SMAP | Monitoramento de publicações e processos eleitorais',
		'description' => 'Acompanhamento automático de publicações e processos eleitorais, com resumos, distribuição e alertas — sem expor dados sigilosos.',
		'lead' => 'A equipe deixa de caçar publicação e processo na mão. Recebe o que mudou, resumido e roteado.',
		'problem' => 'Em período eleitoral, o escritório precisava mobilizar cerca de dez estagiários para consultar publicações oficiais e o PJe, identificar movimentações e encaminhar cada caso.',
		'solution' => 'Centralização de fontes públicas da Justiça Eleitoral, vínculo entre candidatos, processos e responsáveis, resumos com IA e distribuição de notificações. Informação pública organizada, sem dados sigilosos no portfólio.',
		'result' => 'Nas Eleições Municipais de 2024, a operação rodou sem o reforço temporário previsto. A equipe foi para análise jurídica, não para consulta repetitiva.',
		'highlights' => ['Publicações oficiais', 'PJe de 1º e 2º graus', 'Resumos assistidos', 'Roteamento para advogados'],
		'metrics' => [
			['value' => '1.600', 'label' => 'processos eleitorais em 2024'],
			['value' => '2.717', 'label' => 'publicações capturadas em 2024'],
			['value' => '350', 'label' => 'pessoas e entidades acompanhadas'],
			['value' => '4', 'label' => 'advogados vinculados'],
		],
		'technologies' => ['Python', 'Node.js', 'APIs', 'MySQL', 'OpenAI', 'Notificações'],
		'note' => 'Métricas agregadas da base operacional. Nenhum dado pessoal ou processual é exibido.',
	],
	'vitoria' => [
		'name' => 'VitorIA',
		'type' => 'Primeiro atendimento com IA',
		'status' => 'Entregue',
		'status_tone' => 'done',
		'title' => 'VitorIA | Primeiro atendimento no WhatsApp',
		'description' => 'Recepção inicial no WhatsApp para dúvidas recorrentes e encaminhamento do que exige pessoa.',
		'lead' => 'A fila do primeiro atendimento deixa de crescer na mesma proporção do volume de mensagens.',
		'problem' => 'Uma loja de material esportivo concentrava o volume em duas atendentes. O crescimento apontava para contratar e treinar uma terceira pessoa.',
		'solution' => 'Integração ao WhatsApp para recepção, interpretação, respostas recorrentes e escalonamento do que pede negociação ou contexto.',
		'result' => 'Parte do primeiro atendimento saiu da fila humana. As atendentes ficaram com as conversas de maior complexidade e valor.',
		'highlights' => ['Triagem automática', 'Dúvidas recorrentes', 'Escalonamento humano', 'Histórico do fluxo'],
		'metrics' => [
			['value' => '2', 'label' => 'atendentes apoiadas'],
			['value' => '24×7', 'label' => 'recepção inicial'],
			['value' => 'Humano', 'label' => 'exceção preservada'],
		],
		'technologies' => ['n8n', 'Chatwoot', 'WhatsApp API', 'OpenAI', 'APIs REST'],
	],
	'guavision' => [
		'name' => 'GuaVision',
		'type' => 'Observabilidade visual de terminais',
		'status' => 'Em operação',
		'status_tone' => 'done',
		'title' => 'GuaVision | Observabilidade visual de ATMs',
		'description' => 'A tela do terminal vira fonte de monitoramento, com filtro automático de mensagens conhecidas.',
		'lead' => 'Anomalias que só aparecem na interface deixam de depender de dezenas de sessões abertas.',
		'problem' => 'Parte do comportamento anômalo dos ATMs aparecia só na tela, não nos logs. A equipe mantinha várias sessões abertas para confirmar relato de usuário.',
		'solution' => 'Captura das telas, reconhecimento de mensagens conhecidas, filtro do que importa e notificação — sem exibir identificadores internos neste portfólio.',
		'result' => 'Aproximadamente 90% das mensagens de problema passaram a ser capturadas e filtradas automaticamente.',
		'highlights' => ['Captura remota', 'Mensagens conhecidas', 'Filtro de eventos', 'Notificação'],
		'metrics' => [
			['value' => '≈90%', 'label' => 'das mensagens capturadas'],
			['value' => 'ATM', 'label' => 'observabilidade visual'],
			['value' => 'Auto', 'label' => 'filtro e alerta'],
		],
		'technologies' => ['Python', 'Visão computacional', 'OCR', 'APIs', 'Notificações'],
	],
];
